# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: N.T.T.
email: dean.silfen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  On Tuesday we must listen to at least 2 albums by a female fronted act.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tues.rocks" # the base hostname & protocol for your site
twitter_username: deanrex
github_username:  djds23

# Build settings
markdown: kramdown
